### ISSUE TITLE
Bug: No coercion operator is defined between types 'System.TimeSpan' and 'System.Int64'.

### ISSUE THREAD

**Issue by Garios** [mikependon/RepoDb#1033]
Hi, I updated from 1.12.9 to 1.12.10 (using C#). The following property-handler doesn't work. It works for reading, but not for writing (insert/update). (I mentioned it in #1021)

```csharp
public class TestClass
{
  public long ID {get;set;}
  public TimeSpan TestFieldTimeSpan {get;set;}
}
```

```csharp
    public class PropertyHandlerTimeSpan : IPropertyHandler<long, TimeSpan>
    {
        public TimeSpan Get(long p, ClassProperty property) => new TimeSpan(p);

        public long Set(TimeSpan p, ClassProperty property) => p.Ticks;
    }
```

```csharp
FluentMapper.Entity<TestClass>().PropertyHandler<PropertyHandlerTimeSpan>(p=>p.TestFieldTimeSpan );
```

Exception: "Compiler.Entity/Object.Property: Failed to convert the value expression for property handler 'PropertyHandlerTimeSpan'. ClassProperty :: Name = TestFieldTimeSpan (System.TimeSpan), DeclaringType = TestClass
```
   at RepoDb.Reflection.Compiler.GetEntityInstancePropertyValueExpression(Expression entityInstanceExpression, ClassProperty classProperty, DbField dbField)
   at RepoDb.Reflection.Compiler.GetDataEntityDbParameterValueAssignmentExpression(ParameterExpression parameterVariableExpression, Expression entityExpression, ParameterExpression propertyExpression, ClassProperty classProperty, DbField dbField, IDbSetting dbSetting)
   at RepoDb.Reflection.Compiler.GetDataEntityParameterAssignmentExpression(ParameterExpression commandParameterExpression, Int32 entityIndex, Expression entityExpression, ParameterExpression propertyExpression, DbField dbField, ClassProperty classProperty, ParameterDirection direction, IDbSetting dbSetting)
   at RepoDb.Reflection.Compiler.GetPropertyFieldExpression(ParameterExpression commandParameterExpression, Expression entityExpression, FieldDirection fieldDirection, Int32 entityIndex, IDbSetting dbSetting)
   at RepoDb.Reflection.Compiler.CompileDataEntityDbParameterSetter(Type entityType, IEnumerable`1 inputFields, IEnumerable`1 outputFields, IDbSetting dbSetting)
   at RepoDb.Reflection.FunctionFactory.CompileDataEntityDbParameterSetter(Type entityType, IEnumerable`1 inputFields, IEnumerable`1 outputFields, IDbSetting dbSetting)
   at RepoDb.FunctionCache.DataEntityDbParameterSetterCache.Get(Type entityType, String cacheKey, IEnumerable`1 inputFields, IEnumerable`1 outputFields, IDbSetting dbSetting)
   at RepoDb.FunctionCache.GetDataEntityDbParameterSetterCompiledFunction(Type entityType, String cacheKey, IEnumerable`1 inputFields, IEnumerable`1 outputFields, IDbSetting dbSetting)
   at RepoDb.Contexts.Providers.UpdateExecutionContextProvider.CreateInternal(Type entityType, IDbConnection connection, String tableName, IEnumerable`1 dbFields, IEnumerable`1 fields, String commandText)
   at RepoDb.Contexts.Providers.UpdateExecutionContextProvider.<CreateAsync>d__2.MoveNext()
```

Inner Exception: "No coercion operator is defined between types 'System.TimeSpan' and 'System.Int64'."
```
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at RepoDb.Reflection.Compiler.ConvertExpressionToTypeExpression(Expression expression, Type toType)
   at RepoDb.Reflection.Compiler.ConvertExpressionToNullableExpression(Expression expression, Type targetNullableType)
   at RepoDb.Reflection.Compiler.ConvertExpressionToPropertyHandlerSetExpressionTuple(Expression expression, ClassProperty classProperty, Type targetType)
   at RepoDb.Reflection.Compiler.ConvertExpressionToPropertyHandlerSetExpression(Expression expression, ClassProperty classProperty, Type targetType)
   at RepoDb.Reflection.Compiler.GetEntityInstancePropertyValueExpression(Expression entityInstanceExpression, ClassProperty classProperty, DbField dbField)
```

**Comment by mikependon** [comment]
I was a bit surprise by this issue as our [Integration Tests](https://github.com/mikependon/RepoDB/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/PropertyHandlerTest.cs) are working. The only difference is just we are using [DateTime to DateTime](https://github.com/mikependon/RepoDB/blob/44c9e32e998ca7c584eddfd33c469a1e9db8f942/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/PropertyHandlerTest.cs#L139) but the others (like [this](https://github.com/mikependon/RepoDB/blob/44c9e32e998ca7c584eddfd33c469a1e9db8f942/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/PropertyHandlerTest.cs#L106)) are almost the same concepts. I can even replicate this issue (just now).

We will fix this one for you as this is a bit critical to be honest. You will receive further updates from us in relation to this.

Working: [RepoDbPropertyHandler-CustomType-Working.zip](https://github.com/mikependon/RepoDB/files/8110081/RepoDbPropertyHandler-CustomType-Working.zip)
Not Working: [RepoDbPropertyHandler-TimeSpan-NotWorking.zip](https://github.com/mikependon/RepoDB/files/8110082/RepoDbPropertyHandler-TimeSpan-NotWorking.zip)

**Comment by mikependon** [comment]
This has just been fixed and it will be available on the next release. Would you be able to let us know if you the fix immediately? Thanks

**Comment by Garios** [comment]
Hi, thank you! I tried it with the current master. Now it works fine! Thanks!! I will wait till the next release for using 1.12.10.
Thanks!

**Comment by mikependon** [comment]
This is the only fix for that (https://github.com/mikependon/RepoDB/commit/fd973c3b7bf413fe6ddf577605b8f13143d60ea4#diff-60f2ffa37fb8c5f1593dd214b314d6b037e40b4a1a3a681a4f1e591dbd1f5652R903), but we covered it by the Integration Tests.

Alternatively, you use the newly release v1.12.10 but you have to make the property nullable.

**Model:**

![image](https://user-images.githubusercontent.com/591015/155291313-7108ba23-01a7-48f0-a27e-1a0056ba40cb.png)

**Table:**

![image](https://user-images.githubusercontent.com/591015/155291349-8bc359f7-6f1c-4752-942c-3ca7be4036ec.png)

**Property Handler:**

![image](https://user-images.githubusercontent.com/591015/155291436-6d190c7b-cb28-4541-9c03-37ca83857774.png)

**Comment by Garios** [comment]
Thank you for this hint, but currently it's not absolutely necessary to use 1.12.10 :wink:

**Comment by Garios** [comment]
Hello Mike,
when do you plan the next release? I need this fix, because of another fix.
kind regards
Juergen

**Comment by mikependon** [comment]
I can issue a new beta for you later. I will update this ticket

**Comment by Garios** [comment]
wow, this would be nice! Thank you!

**Comment by mikependon** [comment]
The latest alpha release has been pushed. Please install the package >= RepoDb v1.13.0-2 and its equivalent extension package.
Note: We cannot issue a beta due to a failing scenario in the latest development branch.

**Comment by mikependon** [comment]
Please be informed of our delta [changes](https://repodb.net/release/core). In this release, we have so many breaking changes. This is the reason why we are having delays on our releases.
