### ISSUE TITLE
Parameters are still created even if property was marked with Ignore

### ISSUE THREAD

**Issue by rdagumampan** [mikependon/RepoDB#12]
When query is executed, the parameter builder still process properties that are marked to Ignore. In this case DateInsertedUtc must be ignored when building the parameter bucket. If the property is not initialized, it will set to default value.

```
[Map("[dbo].[Customer]")]
public class Customer : DataEntity
{
	[Attributes.Ignore(Command.Insert | Command.Update | Command.Merge | Command.InlineUpdate), Primary(true), Map("Id")]
	public int Id { get; set; }

	public Guid GlobalId { get; set; }

	public string FirstName { get; set; }

	public string MiddleName { get; set; }

	public string LastName { get; set; }

	public string Address { get; set; }

	public string Email { get; set; }

	public bool IsActive { get; set; }

	public DateTime LastUpdatedUtc { get; set; }

	[Attributes.Ignore(Command.Update | Command.Insert)]
	public DateTime DateInsertedUtc { get; set; }

	public string LastUserId { get; set; }
}
```

```
[Test]
public void TestInsert()
{
	//arrange
	var repository = new DbRepository<SqlConnection>(RepoDbConnectionString, 0);

	var fixtureData = new Customer
	{
		GlobalId = Guid.NewGuid(),
		FirstName = "Juan",
		LastName = "de la Cruz",
		MiddleName = "Pinto",
		Address = "San Lorenzo, Makati, Philippines 4225",
		IsActive = true,
		Email = "juandelacruz@gmai.com",
		//DateInsertedUtc = DateTime.UtcNow, COMMENTED FOR TESTING
		LastUpdatedUtc = DateTime.UtcNow,
		LastUserId = Environment.UserName
	};

	//act
	repository.Insert(fixtureData);

	//assert
	var customer = repository.Query<Customer>().FirstOrDefault();
	customer.ShouldNotBeNull();
	customer.Id.ShouldNotBe(0);
	customer.GlobalId.ShouldBe(fixtureData.GlobalId);
	customer.FirstName.ShouldBe(fixtureData.FirstName);
	customer.LastName.ShouldBe(fixtureData.LastName);
	customer.MiddleName.ShouldBe(fixtureData.MiddleName);
	customer.Address.ShouldBe(fixtureData.Address);
	customer.Email.ShouldBe(fixtureData.Email);
	customer.IsActive.ShouldBe(fixtureData.IsActive);
	customer.DateInsertedUtc.ShouldBe(fixtureData.DateInsertedUtc);
	customer.LastUpdatedUtc.ShouldBe(fixtureData.LastUpdatedUtc);
	customer.LastUserId.ShouldBe(fixtureData.FirstName);
}
```

System.Data.SqlTypes.SqlTypeException : SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at RepoDb.Extensions.DbConnectionExtension.ExecuteScalar(IDbConnection connection, String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace) in C:\play\RepoDb\RepoDb\Extensions\DbConnectionExtension.cs:line 498
   at RepoDb.DbRepository`1.ExecuteScalar(String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction) in C:\play\RepoDb\RepoDb\DbRepository.cs:line 2058
   at RepoDb.DbRepository`1.Insert[TEntity](TEntity entity, IDbTransaction transaction) in C:\play\RepoDb\RepoDb\DbRepository.cs:line 1094
   at RepoDb.IntegrationTests.TestBasicCrud.TestInsert() in C:\play\RepoDb\RepoDb.IntegrationTests\TestBasicCrud.cs:line 38

**Comment by mikependon** [comment]
Thank you for this findings. Will copy over your integration test project there and merge everything. Will look at this now.

I have introduced new structure at RepoDb master branch and I will place this code there.

**Comment by mikependon** [comment]
I have tested it, I'd merged over the initial Integration Test in the master branch. Seems this is invalid. It works as expected.


            // This would really not equal as you ignore this in the insertion, but is defaulted in the database
            customer.DateInsertedUtc.ShouldBe(fixtureData.DateInsertedUtc);

            // This has been fixed by the TypeMapper.AddMap
            customer.LastUpdatedUtc.ShouldBe(fixtureData.LastUpdatedUtc);

            // This must be Environment.UserName
            customer.LastUserId.ShouldBe(fixtureData.FirstName);

**Comment by mikependon** [comment]
Fixed and is merged at the 'master' branch.
