### ISSUE TITLE
Merge failed when PK column was not passed in the dataset

### ISSUE THREAD

**Issue by rdagumampan** [mikependon/RepoDB#18]
Merge failed when PK column was not passed in the dataset. It used to be working but have now failed after the latest fixes in Master.

Tests available in my fork https://github.com/rdagumampan/RepoDb.

Open the 
```
[Test]
public void TestMergeInsert()
{
	//arrange
	var repository = new DbRepository<SqlConnection>(Constants.TestDatabase);

	var fixtureData = new Customer
	{
		GlobalId = Guid.NewGuid(),
		FirstName = "Juan-MERGED",
		LastName = "de la Cruz-MERGED",
		MiddleName = "Pinto-MERGED",
		Address = "San Lorenzo, Makati, Philippines 4225-MERGED",
		IsActive = true,
		Email = "juandelacruz@gmai.com-MERGED",
		LastUpdatedUtc = DateTime.UtcNow,
		LastUserId = Environment.UserName
	};

	//act
	repository.Merge(fixtureData);

	//assert
	var customer = repository.Query<Customer>(new { fixtureData.GlobalId }).FirstOrDefault();
	customer.ShouldNotBeNull();
	customer.Id.ShouldNotBe(0);
	customer.GlobalId.ShouldBe(fixtureData.GlobalId);
	customer.FirstName.ShouldBe(fixtureData.FirstName);
	customer.LastName.ShouldBe(fixtureData.LastName);
	customer.MiddleName.ShouldBe(fixtureData.MiddleName);
	customer.Address.ShouldBe(fixtureData.Address);
	customer.Email.ShouldBe(fixtureData.Email);
	customer.IsActive.ShouldBe(fixtureData.IsActive);
	customer.LastUpdatedUtc.ShouldBe(fixtureData.LastUpdatedUtc);
	customer.LastUserId.ShouldBe(fixtureData.LastUserId);
}
```

```
System.Data.SqlClient.SqlException : Must declare the scalar variable "@Id".
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

```

**Comment by rdagumampan** [comment]
Closed as As Designed.
Id must be passed when Merge is called. The internal generated SQL needs the column for identifying source and destination.
