### ISSUE TITLE
Bug: Calling InsertAll With Map Attribute leads to System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#274]
**Model:**

	namespace RepoDbTest.Models
	{
		public class Person
		{
			[Map("Id")]
			public int PersonId { get; set; }
			[Map("SSN")]
			public Guid SocialSecurityNumber { get; set; }
			[Map("Name")]
			public string CompleteName { get; set; }
			[Map("DateOfBirth")]
			public DateTime? DateOfBirth { get; set; }
			[Map("DateRegistered")]
			public DateTimeOffset DateRegistered { get; set; }
			public string LastUserId { get; set; }
			public string OtherProperty { get; set; }
		}
	}

**Code:**

        private static void TestInsertAll()
        {
            var people = GetPeople();
            using (var connection = new SqlConnection(m_connectionString))
            {
                connection.InsertAll(people);
                var tableName = ClassMappedNameCache.Get<Person>();
                var fields = DbFieldCache
                    .Get(connection, tableName)
                    .Select(f => new Field(f.Name, f.Type));
                connection.InsertAll(tableName, people, fields: fields, trace: new CustomTrace());
            }
        }

**Stack:**

	at RepoDb.Reflection.FunctionFactory.GetDataEntityPropertySetterFromDbCommandParameterFunction[TEntity](Field field, String parameterName, Int32 index)
	at RepoDb.FunctionCache.GetDataEntityPropertySetterFromDbCommandParameterFunctionCache`1.Get(Field field, String parameterName, Int32 index)
	at RepoDb.DbConnectionExtension.<>c__DisplayClass177_0`1.<InsertAllInternalBase>b__0(Int32 batchSizeValue)
	at RepoDb.Contexts.Execution.InsertAllExecutionContextCache`1.Get(String tableName, IEnumerable`1 fields, Int32 batchSize, Func`2 callback)
	at RepoDb.DbConnectionExtension.InsertAllInternalBase[TEntity](IDbConnection connection, String tableName, IEnumerable`1 entities, Int32 batchSize, IEnumerable`1 fields, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder, Boolean skipIdentityCheck)
	at RepoDb.DbConnectionExtension.InsertAllInternal[TEntity](IDbConnection connection, IEnumerable`1 entities, Int32 batchSize, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
	at RepoDbTest.Program.TestInsertAll() in C:\Users\MIPEN\source\repos\RepoDbTest\RepoDbTest\Program.cs:line 53
	at RepoDbTest.Program.Main(String[] args) in C:\Users\MIPEN\source\repos\RepoDbTest\RepoDbTest\Program.cs:line 18

**Comment by mikependon** [comment]
USE [Test]
	GO

	/****** Object:  Table [dbo].[Person]    Script Date: 9/19/2019 8:40:19 AM ******/
	SET ANSI_NULLS ON
	GO

	SET QUOTED_IDENTIFIER ON
	GO

	CREATE TABLE [dbo].[Person](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[SSN] [uniqueidentifier] NOT NULL,
		[Name] [nvarchar](256) NOT NULL,
		[DateOfBirth] [datetime2](5) NOT NULL,
		[DateRegistered] [datetimeoffset](7) NOT NULL,
		[LastUserId] [nvarchar](128) NOT NULL,
	 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO

**Comment by mikependon** [comment]
This will be available at version > v1.9.9-beta1.

**Comment by Pazout** [comment]
![image](https://user-images.githubusercontent.com/5221083/171436969-13e7d7ba-60b1-4347-8e91-52eed57f0ca2.png)

I still have a problem with this error.
RepoDb.MySql 1.1.6

**Comment by mikependon** [comment]
Are you able to share the following?

- The model class
- The table schema
- The mapping you did

We will simulate this case on our end and see if this is a valid one or there is an alternative recommendation.
