### ISSUE TITLE
Bug: SqlDbHelper.GetFields is failing if the transaction object is present.

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#278]
at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at RepoDb.DbHelpers.SqlDbHelper.GetFields[TDbConnection](TDbConnection connection, String tableName)
   at RepoDb.DbFieldCache.GetInternal[TDbConnection](TDbConnection connection, String tableName)
   at RepoDb.DbConnectionExtension.<>c__DisplayClass167_0`2.<InsertInternalBase>b__0()
   at RepoDb.Contexts.Execution.InsertExecutionContextCache`1.Get(String tableName, IEnumerable`1 fields, Func`1 callback)
   at RepoDb.DbConnectionExtension.InsertInternalBase[TEntity,TResult](IDbConnection connection, String tableName, TEntity entity, IEnumerable`1 fields, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder, Boolean skipIdentityCheck)
   at RepoDb.DbConnectionExtension.InsertInternal[TEntity,TResult](IDbConnection connection, TEntity entity, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDbTest.Program.<>c__DisplayClass1_1.<Main>b__0(Person p) in C:\Users\MIPEN\source\repos\RepoDbTest\RepoDbTest\Program.cs:line 25
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RepoDbTest.Program.Main(String[] args) in C:\Users\MIPEN\source\repos\RepoDbTest\RepoDbTest\Program.cs:line 25

**Comment by mikependon** [comment]
FYI: @tabishfriend

**Comment by mikependon** [comment]
The fix has been checked-in to the master branch. The fix will also be available to version > v1.9.9-beta4.
