### ISSUE TITLE
Calls to Repository.Query resulted to an Intermittent Exception

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#6]
Intermittent: Exception below is being thrown when repository.Query is called.

``
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at RepoDb.Reflection.TypeCache.Get(TypeTypes type)
   at RepoDb.Reflection.ReflectionFactory.CreateTypes(TypeTypes[] types)
   at RepoDb.Reflection.TypeArrayCache.Get(TypeTypes[] type)
   at RepoDb.Reflection.DelegateFactory.GetDataReaderToDataEntityDelegate[TEntity](DbDataReader reader)
   at RepoDb.Reflection.DelegateCache.GetDataReaderToDataEntityDelegate[TEntity](DbDataReader reader)
   at RepoDb.Reflection.DataReaderConverter.ToEnumerable[TEntity](DbDataReader reader)
   at RepoDb.Extensions.DbConnectionExtension.ExecuteQuery[TEntity](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace)
   at RepoDb.DbRepository`1.ExecuteQuery[TEntity](String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction)
   at RepoDb.DbRepository`1.Query[TEntity](QueryGroup where, IDbTransaction transaction, Nullable`1 top, IEnumerable`1 orderBy, String cacheKey)
   at RepoDb.DbRepository`1.Query[TEntity](Object where, IDbTransaction transaction, Nullable`1 top, IEnumerable`1 orderBy, String cacheKey)
   at LocalVisitLogHistoricalDataProcessor.Program.ProcessClassifications() in C:\Users\MIPEN\Desktop\LocalVisitLogHistoricalDataProcessor\LocalVisitLogHistoricalDataProcessor\Program.cs:line 111
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
``

**Comment by mikependon** [comment]
Introduce a locking (synclock) when adding an item on the caches.
