### ISSUE TITLE
Exceptions occur running in Parallel

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#7]
An exception is being thrown if running multiple operations in parallel using Task.Factory.StartNew.

``
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at RepoDb.PropertyCache.Get[TEntity](Command command)
   at RepoDb.PropertyMapNameCache.Get[TEntity](Command command)
   at RepoDb.QueryBuilder`1.Fields(Command command)
   at RepoDb.SqlDbStatementBuilder.CreateQuery[TEntity](QueryBuilder`1 queryBuilder, QueryGroup where, Nullable`1 top, IEnumerable`1 orderBy)
   at RepoDb.DbRepository`1.Query[TEntity](QueryGroup where, IDbTransaction transaction, Nullable`1 top, IEnumerable`1 orderBy, String cacheKey)
   at RepoDb.DbRepository`1.Query[TEntity](Object where, IDbTransaction transaction, Nullable`1 top, IEnumerable`1 orderBy, String cacheKey)
   at LocalVisitLogHistoricalDataProcessor.Program.ProcessClassifications() in C:\Users\MIPEN\Desktop\LocalVisitLogHistoricalDataProcessor\LocalVisitLogHistoricalDataProcessor\Program.cs:line 119
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
``

**Comment by mikependon** [comment]
Fixed at 1.1.6 release.

**Comment by mikependon** [comment]
Fixed at 1.1.6 release.
