### ISSUE TITLE
Does Postgresql support querying on enums in non-raw form?

### ISSUE THREAD

**Issue by gloriousjob** [mikependon/RepoDB#787]
I'm trying to use Postgresql enums (database first) in my project but it tosses an error. Am I doing something wrong or is this not supported?
My webapi get looks like this:
```
[HttpGet]
public IEnumerable<Person> Get()
{
    var ConnectionString = "Host=localhost;Username=postgres;Password=postgres;Database=test";
    using (var connection = new NpgsqlConnection(ConnectionString))
    {
        var name2 = connection.Query<Person>(e => e.Gender == Gender.Male);
        return name2;
    }
}
```

Here's the error:
System.InvalidCastException: Can't write CLR type TestApi.Data.Gender with handler type TextHandler
   at lambda_method8(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at RepoDb.DbConnectionExtension.ExecuteQueryInternalForType[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.ExecuteQueryInternal[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.QueryInternalBase[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.QueryInternal[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.Query[TEntity](IDbConnection connection, Expression`1 where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at TestApi.Controllers.WeatherForecastController.Get() in C:\Users\glori\source\repos\TestApi\TestApi\Controllers\WeatherForecastController.cs:line 39
   at lambda_method2(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I'm trying to use a class similar to the example in the postgresql page on RepoDB just to see if I can get this working (using a WebApi project):
```
namespace TestApi.Data
{
    public enum Gender
    {
        Male,
        Female
    }
}

namespace TestApi.Data
{
    public class Person
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Gender Gender { get; set; }
    }
}
```
The other change I've done is I have this in Configuration because I want enums to return their string value instead of int:
```
services.AddControllers().AddJsonOptions(opts =>
{
    opts.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
```

Side note: I did get this working but would like to use the non-raw form if possible:

```
[HttpGet]
public IEnumerable<Person> Get()
{
    var ConnectionString = "Host=localhost;Username=postgres;Password=postgres;Database=test";
    using (var connection = new NpgsqlConnection(ConnectionString))
    {
        var gender = Gender.Male;
        var sql = $"SELECT * FROM \"Person\" WHERE \"Gender\" = '{gender}';";
        var name = connection.ExecuteQuery<Person>(sql);
        return name;
    }
}
```

**Comment by mikependon** [comment]
The problem you mentioned above is a problem to the Npgsql driver which I already reported directly to Shay Rojansky, the creator.

But in RepoDB, the answer is YES, it should be supported only of your column type is STRING or INTEGER in your database table and did not use the custom type from the PostgreSQL itself. We had added a logic to parse it specially to PostgreSQL database.

Your problem seems to be very basic for ENUM to be supported and we had it covered from [here](https://github.com/mikependon/RepoDB/blob/master/RepoDb.PostgreSql/RepoDb.PostgreSql.IntegrationTests/EnumTests.cs).

I want to help further, can you share your table schema?

**Comment by mikependon** [comment]
Wait, it seems I pre-assume that your problem is in the compiler, but it is not. It seems to be at the query expression in which by default RepoDB is using the conversion of ENUMs into TEXT.

Can you explicitly use the mapping to define the conversion to INT like below?

`FluentMapper.Person<Person>().DbType(e => e.Gender, DbType.Int32);`

Or via type level like below.

`FluentMapper.Type<Gender>().DbType(DbType.In32)`

Or the generalized setting as mentioned on our documentation [here](https://repodb.net/feature/enumeration#default-conversion).

**Comment by mikependon** [comment]
If that does not work, then please do share your table schema.

**Comment by gloriousjob** [comment]
So the question is on when the PostgreSQL has an ENUM column type in the database. This is desired because we have used string in the past and people mistype a value by one letter and we lose entries.

Here are the two create scripts:
CREATE TYPE public."Gender" AS ENUM
    ('Male', 'Female');

CREATE TABLE public."Person"
(
    "Id" bigint NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Age" integer,
    "Gender" "Gender",
    CONSTRAINT "Person_pkey" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

**Comment by mikependon** [comment]
You can use STRING or INT type and have your model property as an ENUM, all will be handled by RepoDB seemlessly. Have you tried that?

In relation to the PG Types, RepoDB does not do any translation in between, I expect it would work as it is, but is seems not.

We will investigate. 😄

**Comment by gloriousjob** [comment]
I'm assuming when you say type, you mean in PG and model means in C#. I haven't since the goal here is to have the enum in the PG database since we have had issues with people entering bad data into the database directly (int's can easily be confused and string's can be mistyped). I appreciate that you're investigating.

**Comment by mikependon** [comment]
@gloriousjob - please be reminded that in RepoDB you can use a column with type `TEXT/INTEGER` and have the equivalent model property type as an `Enum`.

RepoDB will do the job for you. It will work like a PG Enum type, and with this you are enforcing the proper value into the database (based on the enum values of the property, but not from the input of the user somewhere).

Of course, we will investigate the PG Enum type, but this is on queue for future release. Hope you can rectify your issue by using either the `TEXT/INTEGER` column type.

**Comment by gloriousjob** [comment]
Thanks, @mikependon. The DB that I'm working with will have multiple avenues of manipulation so I'd like to be sure that the database is enforcing the enum.
I've also learned that even if using Raw SQL, the enum names need to be allowed in c# (case can be different but needs to match otherwise) or the translator fails. So it sounds like I'll just need to continue using Raw SQL and the other form may come out in a future release.

I might also consider using a check constraint rather than an enum and taking the text route. The only thing I don't like about that is it doesn't give a nice dropdown in the database gui (not critical), it needs more space and I need separate constraints even if they're identical in columns.

So sounds like the answer to my question is: no but it should be coming.

**Comment by gloriousjob** [comment]
Hi @mikependon, I altered the Gender column to be of text type in Postgres and I'm still getting the same error. Is there something else I need to do?

**Comment by mikependon** [comment]
It should work automatically without doing anything else specially if you are using the entity-based operations (i.e.: `Query<T>`, `Merge<T>`, etc). It has an exception if your column type is non-text (i.e: `INTEGER`, `DOUBLE`, etc) and you need to follow the instruction as explained [here](https://repodb.net/feature/enumeration#default-conversion).

Anyway, I will play around with this later and will get back to you. Hope that is okay?

**Comment by mikependon** [comment]
The issue can be replicated on this small project ([PostgreSqlEnum.zip](https://github.com/mikependon/RepoDB/files/6214555/PostgreSqlEnum.zip)).
