### ISSUE TITLE
Bug: Dynamic insertion via Dictionary<string, object> is failing 

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#791]
### Bug Description

An exception is being thrown when inserting a dictionary object via dynamic insertion.

**Exception Message:**

```csharp
RepoDb.Exceptions.EmptyException
  HResult=0x80131500
  Message=The list of insertable fields must not be null or empty for 'Person'.
  Source=RepoDb
  StackTrace:
   at RepoDb.StatementBuilders.BaseStatementBuilder.CreateInsert(QueryBuilder queryBuilder, String tableName, IEnumerable`1 fields, DbField primaryField, DbField identityField, String hints)
   at RepoDb.StatementBuilders.SqlServerStatementBuilder.CreateInsert(QueryBuilder queryBuilder, String tableName, IEnumerable`1 fields, DbField primaryField, DbField identityField, String hints)
   at RepoDb.CommandTextCache.GetInsertTextInternal(InsertRequest request, IEnumerable`1 fields)
   at RepoDb.CommandTextCache.GetInsertText(InsertRequest request)
   at RepoDb.Contexts.Providers.InsertExecutionContextProvider.Create[TEntity](IDbConnection connection, String tableName, IEnumerable`1 fields, String hints, IDbTransaction transaction, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.InsertInternalBase[TEntity,TResult](IDbConnection connection, String tableName, TEntity entity, IEnumerable`1 fields, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.InsertInternal[TEntity,TResult](IDbConnection connection, String tableName, TEntity entity, IEnumerable`1 fields, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.Insert[TEntity](IDbConnection connection, String tableName, TEntity entity, IEnumerable`1 fields, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
   at DynamicDemoProject.Program.DoInsertViaDictionary() in C:\Users\MichaelP\Source\Repos\GitHub\Tech-Talks\phinug\Projects\DynamicDemoProject\DynamicDemoProject\Program.cs:line 102
   at DynamicDemoProject.Program.Main(String[] args) in C:\Users\MichaelP\Source\Repos\GitHub\Tech-Talks\phinug\Projects\DynamicDemoProject\DynamicDemoProject\Program.cs:line 29
```

**Schema and Model:**

Schema:

```
USE [DemoRepoDB]
GO

/****** Object:  Table [dbo].[Person]    Script Date: 2/17/2021 2:51:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Person](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[CreatedDateUtc] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Person] ADD  CONSTRAINT [DF_Person_CreatedDateUtc]  DEFAULT (getutcdate()) FOR [CreatedDateUtc]
GO
```

We used the dynamic object.

![image](https://user-images.githubusercontent.com/591015/111376779-3068dc80-86a0-11eb-9d53-7876fca99062.png)

**Library Version:**

Example: RepoDb v1.12.8-beta4 and RepoDb.SqlServer v1.1.3

**Comment by mikependon** [comment]
Related to #789.
