### ISSUE TITLE
Question: Are multiple resultsets supported in stored procedures?

### ISSUE THREAD

**Issue by veenroid** [mikependon/RepoDB#823]
`CommandType.Text` works just as shown in the documentation.
```csharp            
using var cn = Connection;
var cmd = "SELECT * FROM dbo.[User]; SELECT g.* FROM dbo.[Group] g JOIN dbo.GroupMembership gm ON g.GroupId = gm.GroupId AND gm.UserId = @UserId";
using var result = cn.ExecuteQueryMultiple(cmd, new { UserId = id }, CommandType.Text);
var user = result.Extract<User>(false).FirstOrDefault();
result.NextResult();
user.Groups = result.Extract<Group>().AsList();
```

`CommandType.StoredProcedure` throws a `System.NotSupportedException`
```csharp
using var cn = Connection;
using var result = cn.ExecuteQueryMultiple("Exec dbo.usp_UserSelect @UserId", new { UserId = id }, CommandType.StoredProcedure);
var user = result.Extract<User>(false).FirstOrDefault();
result.NextResult();
user.Groups = result.Extract<Group>().AsList();
```
Here's the sp DDL:
```sql
CREATE PROCEDURE dbo.usp_UserSelect (@UserId int) AS
    SELECT * FROM dbo.[User] WHERE UserId = @UserId
    SELECT g.* FROM dbo.[Group] g
        JOIN dbo.GroupMembership gm ON g.GroupId = gm.GroupId AND gm.UserId = @UserId
```
Exception Message:
```
System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues. Path: $.TargetSite.DeclaringType.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported and should be avoided since they can lead to security issues.
   at System.Text.Json.Serialization.Converters.TypeConverter.Write(Utf8JsonWriter writer, Type value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
```

**Comment by mikependon** [comment]
The `CommandType.StoredProcedure` only requires a single command text which is the name of the stored procedure (with or without the schema). In your case, you should call it like below.

```csharp
using var cn = Connection;
using var result = cn.ExecuteQueryMultiple("dbo.usp_UserSelect", new { UserId = id }, CommandType.StoredProcedure);
var user = result.Extract<User>(false).FirstOrDefault();
result.NextResult();
user.Groups = result.Extract<Group>().AsList();
```

Notice that you need to remove the `EXEC` keyword as it is not an adhoc execution.

Alternatively, as you mentioned above, you can also call it via `EXEC` command (see below).

```csharp
using var cn = Connection;
using var result = cn.ExecuteQueryMultiple("EXEC dbo.usp_UserSelect @UserId", new { UserId = id }, CommandType.Text);
var user = result.Extract<User>(false).FirstOrDefault();
result.NextResult();
user.Groups = result.Extract<Group>().AsList();
```

**Comment by veenroid** [comment]
Many thanks. Works like a charm. Loving it!
