### ISSUE TITLE
Bug: Login failed for user

### ISSUE THREAD

**Issue by markjackmilian** [mikependon/RepoDB#838]
### Bug Description

When i execute a  this.DbRepository.ExecuteQueryAsync i get the following error.
This error occurs only when use a named instance in connectionstring.
I'm using DbRepository.
It occurs **ONLY** when I run the app on **Mac**. On windows it is working correctly.

I'm using this connectionstring
Server=192.168.50.109\\MSSQLSERVER02;user id=XXX;password=XXXX;Database=XXXXX

**Exception Message:**
Unable to open the database "XXXX" required by the login account. Login failed.
Login failed for user 'XXX'.

```csharp
Microsoft.Data.SqlClient.SqlException (0x80131904): Impossibile aprire il database "XXXX" richiesto dall'account di accesso. Accesso non riuscito.
Accesso non riuscito per l'utente 'XXX'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at RepoDb.DbConnectionExtension.EnsureOpen(IDbConnection connection)
   at RepoDb.DbConnectionExtension.CreateDbCommandForExecution(IDbConnection connection, String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction, Type entityType, IEnumerable`1 dbFields, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.ExecuteQueryInternal(IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.ExecuteQuery(IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache)
   at RepoDb.DbRepository`1.ExecuteQuery(String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, IDbTransaction transaction)
   at Sinergest.Mobile.Domain.Repositories.UtenteAspNetRepository.GetUtenteByUserNameAsync(String username) in /Users/marco/Projects/Sinergest.Mobile.WebApi/Sinergest.Mobile.WebApi/Sinergest.Mobile.Domain/Repositories/IUtenteAspNetRepository.cs:line 51
   at Sinergest.Mobile.Domain.Services.MembershipService.ValidateUserAsync(String username, String password) in /Users/marco/Projects/Sinergest.Mobile.WebApi/Sinergest.Mobile.WebApi/Sinergest.Mobile.Domain/Services/IMembershipService.cs:line 48
ClientConnectionId:6a0a544a-4a09-4d9b-870e-8c331182b580
Error Number:4060,State:1,Class:11
```

```csharp
var cmd = @"
                        SELECT 
	                        U.UserId,
                            U.UserName,
                            U.LoweredUserName,
                            M.Password,
                            M.PasswordSalt,
                            M.PasswordFormat,
                            M.Email
                        FROM aspnet_Users U
                        INNER JOIN aspnet_Membership M ON M.UserId=U.UserId
                        WHERE U.UserName=@USERNAME";

            var aspnetUsers = await this.DbRepository.ExecuteQueryAsync(cmd, new {USERNAME = username});
```

**Library Version:**

Example: RepoDb v1.12.7 and RepoDb.SqlServer v1.1.3

**Comment by mikependon** [comment]
Hey mate, thanks for reporting this issue. Have you isolated whether this is an ADO.net issue?

**Comment by markjackmilian** [comment]
> Hey mate, thanks for reporting this issue. Have you isolated whether this is an ADO.net issue?

Hi!
Thanks to your reply i found the problem.
The connection error was caused by Microsoft.Data.SqlClient 2.1.1 implicit referenced by RepoDB.
Manually add a reference to 2.1.3 solve the issue!

**Comment by mikependon** [comment]
It sounds to me that we also need to update the reference to MDS 2.1.3. Thanks for this input.
