### ISSUE TITLE
Bug: The ENUM type of Postgre (DB) is not being handled properly in RepoDb.PostgreSql. #395

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#854]
Reported by @orthoxerox at #395.

@mikependon This still doesn't work if the enum is used in the where clause:

```c#
var people = connection.Query<Person>(where: p => p.DominantHand == Hand.Right);
//I've been renaming stuff to understand why my main program failed when this snipped didn't
```

results in:

```
Unhandled exception. System.InvalidCastException: Can't write CLR type Sandbox.Program+Hand with handler type TextHandler
   at lambda_method5(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at RepoDb.DbConnectionExtension.ExecuteQueryInternalForType[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.ExecuteQueryInternal[TResult](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, String tableName, Boolean skipCommandArrayParametersCheck)
   at RepoDb.DbConnectionExtension.QueryInternalBase[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.QueryInternal[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at RepoDb.DbConnectionExtension.Query[TEntity](IDbConnection connection, Expression`1 where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder)
   at Sandbox.Program.QueryPeople() in C:\...\Sandbox\Program.cs:line 99
   at Sandbox.Program.Main(String[] args) in C:\...\Sandbox\Program.cs:line 41
```

**Comment by mikependon** [comment]
@orthoxerox, please continue here.

**Comment by orthoxerox** [comment]
One more thing: `Nullable<SomeEnum>` doesn't work either. I'll push a branch with failing tests to my fork in a few hours.

Upd: #855

**Comment by epicbugs** [comment]
The error is still happening with RepoDb.PostgreSql (1.1.4) and integer type column in database.

> System.InvalidCastException: Can't write CLR type SomeEnum with handler type Int32Handler

Only workaround I found was to implement `IPropertyHandler<int, T> where T : Enum`.

Would it be possible to have some bugfix or feature so that no handler is required?
